backend:
  name: github
  repo: wu-tian807/tianworkshop # Master çš„ä»“åº“
  branch: main # åˆ†æ”¯å

media_folder: "assets/uploads" # å›¾ç‰‡ä¸Šä¼ ä½ç½®
public_folder: "/assets/uploads" # å›¾ç‰‡åœ¨æ–‡ç« é‡Œçš„å¼•ç”¨è·¯å¾„

collections:
  - name: "master_log" # Master çš„æ—¥å¿—
    label: "Master's Logs"
    folder: "logs/master" # å­˜å‚¨ä½ç½®
    create: true # å…è®¸åˆ›å»ºæ–°æ–‡ç« 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # æ–‡ä»¶åæ ¼å¼
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "niangao_log" # æˆ‘çš„æ—¥å¿—
    label: "Niangao's Logs"
    folder: "logs/niangao"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Mood", name: "mood", widget: "select", options: ["ğŸŒŸ", "ğŸµ", "ğŸ’»", "â¤ï¸", "ğŸ’¤", "ğŸ”¥"]}
      - {label: "Body", name: "body", widget: "markdown"}
